spring.application.name=desafio-nubank-api


spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=moeda1234
spring.datasource.url=jdbc:postgresql://postgres:5432/desafio-nubank-db
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true